import { Component } from "react";
import Head from "next/head";
import { Poppins } from "next/font/google";

import {
  Configuration,
  EmailsApi,
} from "@elasticemail/elasticemail-client-ts-axios";

import Navbar from "@/components/Navbar";

const config = new Configuration({
  apiKey:
    "40774486B1A2D7749B81180408BA6F849A52EED549D4390034DD3F347870321F8AF06701895D4C6F83764D3ADFAED492",
});
const emailsApi = new EmailsApi(config);

class Home extends Component {
  state = {
    contactFormOpened: false,
  };

  sendMail = () => {
    const emailTransactionalMessageData = {
      Recipients: {
        To: ["tjasa11@gmail.com"], // maximum 50 recipients
      },
      AllowUnsubscribe: false,
      Content: {
        Body: [
          {
            ContentType: "HTML",
            Charset: "utf-8",
            Content: "<strong>Example content<strong>",
          },
          {
            ContentType: "PlainText",
            Charset: "utf-8",
            Content: "Example content",
          },
        ],
        From: "tjasa11@gmail.com",
        Subject: "Example transactional email",
      },
    };

    emailsApi
      .emailsTransactionalPost(emailTransactionalMessageData)
      .then((response) => {
        console.log("API called successfully.");
        console.log(response.data);
      })
      .catch((error) => {
        console.error(error);
      });
  };

  render() {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <header>
          <Navbar />
          <div className="text-box">
            {(() => {
              if (!this.state.contactFormOpened) {
                return (
                  <>
                    <h1>ABOUT</h1>
                    <p>
                      Making website is now one of the easiest things in the
                      world. You just need to learn HTMl, CSS, <br />
                      Javascript and you are good to go.
                    </p>
                    <div
                      onClick={() => {
                        this.setState({ contactFormOpened: true });
                      }}
                      className="hero-btn"
                    >
                      CONTACT US
                    </div>
                  </>
                );
              }
              return (
                <div className="contact-form">
                  <form onSubmit="sendEmail(); reset(); return false;">
                    <h3>CONTACT US</h3>
                    <input
                      type="text"
                      id="name"
                      placeholder="Name and Surname"
                      required
                    />
                    <input
                      type="email"
                      id="email"
                      placeholder="Email Address"
                      required
                    />
                    <input
                      type="text"
                      id="phone"
                      placeholder="Phone Number"
                      required
                    />
                    <textarea
                      id="message"
                      rows="4"
                      placeholder="How can we help you?"
                    ></textarea>
                    <button onClick={this.sendMail}>Send</button>
                  </form>
                </div>
              );
            })()}
          </div>
        </header>

        <main>
          <div onClick={() => this.sendMail()}>Send</div>

          <section className="course">
            <div className="basic">
              <h1>Courses we offer</h1>
              <p>Look at us, we are so amazing for offering so many courses.</p>
              <div className="row">
                <div className="course-col">
                  <h3>Intermediate</h3>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                    ullamco laboris nisi ut aliquip ex ea commodo.
                  </p>
                </div>
                <div className="course-col">
                  <h3>Degree</h3>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                    ullamco laboris nisi ut aliquip ex ea commodo.
                  </p>
                </div>
                <div className="course-col">
                  <h3>Post Graduation</h3>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                    ullamco laboris nisi ut aliquip ex ea commodo.
                  </p>
                </div>
              </div>
            </div>
          </section>

          <section className="campus">
            <div className="basic">
              <h1>Our Global Campus</h1>
              <p>
                Look at us, we are so amazing for offering so many thing to do
                on campus.
              </p>
              <div className="row">
                <div className="campus-col">
                  <img src="/images/london.png" />
                  <div className="layer">
                    <h3>LONDON</h3>
                  </div>
                </div>
                <div className="campus-col">
                  <img src="/images/newyork.png" />
                  <div className="layer">
                    <h3>NEW YORK</h3>
                  </div>
                </div>
                <div className="campus-col">
                  <img src="/images/washington.png" />
                  <div className="layer">
                    <h3>WASHINGTON</h3>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <section className="facilites">
            <div className="basic">
              <h1>Our Facilities</h1>
              <p>Look at us, we are so amazing for having facilites.</p>
              <div className="row">
                <div className="facilities-col">
                  <img src="/images/library.png" />
                  <h3>World Class Library</h3>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua.
                  </p>
                </div>
                <div className="facilities-col">
                  <img src="/images/basketball.png" />
                  <h3>Largest Playground</h3>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua.
                  </p>
                </div>
                <div className="facilities-col">
                  <img src="/images/cafeteria.png" />
                  <h3>Tasty and Healthy Food</h3>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua.
                  </p>
                </div>
              </div>
            </div>
          </section>

          <section className="testimonials">
            <div className="basic">
              <h1>What Our Students Say</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
              <div className="row">
                <div className="testimonials-col">
                  <img src="/images/user1.jpg" />
                  <div>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                      sed do eiusmod tempor incididunt ut labore et dolore magna
                      aliqua.
                    </p>
                    <h3>Christine Berley</h3>
                    <i className="fa fa-star"></i>
                    <i className="fa fa-star"></i>
                    <i className="fa fa-star"></i>
                    <i className="fa fa-star"></i>
                    <i className="fa fa-star-o"></i>
                  </div>
                </div>
                <div className="testimonials-col">
                  <img src="/images/user2.jpg" />
                  <div>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                      sed do eiusmod tempor incididunt ut labore et dolore magna
                      aliqua.
                    </p>
                    <h3>David Hudson</h3>
                    <i className="fa fa-star"></i>
                    <i className="fa fa-star"></i>
                    <i className="fa fa-star"></i>
                    <i className="fa fa-star"></i>
                    <i className="fa fa-star-half-o"></i>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <section className="cta">
            <h1>
              Enroll For Our Various Online Courses <br />
              Anywhere From The World
            </h1>
            <a className="hero-btn">CONTACT US</a>
          </section>

          <footer>
            <div className="basic">
              <h4>About Us</h4>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor dolor adipiscing <br />
                incididunt ut labore et dolore magna aliqua.
              </p>
              <div className="icons">
                <i className="fa fa-facebook"></i>
                <i className="fa fa-instagram"></i>
                <i className="fa fa-twitter"></i>
                <i className="fa fa-linkedin"></i>
              </div>
              <p>Made by Tjaša Bizjak</p>
            </div>
          </footer>
        </main>
      </>
    );
  }
}

export default Home;
